version: '3.8'
services:
   db:
    container_name: postgres-db
    image: postgres:latest
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./apps/server/.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:





